---

- name: Install KVM
  yum:
    name:
      - qemu-kvm
      - libvirt
      - virt-install
      - bridge-utils
      - libselinux-python
    state: present
  become: yes
  delegate_to: "{{ kvm_install_host }}"

- name: Start/Enable libvirtd
  systemd: name=libvirtd enabled=yes state=started
  become: yes
  delegate_to: "{{ kvm_install_host }}"

- name: Check if the libvirt module is loaded
  shell: "lsmod | grep kvm | wc -l"
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  register: libvirtd_mod_loaded

- name: If the libvirt module is loaded, it should fail
  fail:
    msg: "libvirt module is not loaded. Check bios configuration"
  when: libvirtd_mod_loaded.stdout == '0'